[package]
name = "lc-3-vm"
version = "0.1.0"
authors = ["Joren Van Onder <joren@jvo.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
